#!/bin/bash

mkdir build
cd build
#git clone https://github.com/alphacep/vosk-api.git
git clone git@github.com:alphacep/vosk-api.git
cd vosk-api/java/lib/src/main/resources
wget -q https://repo1.maven.org/maven2/com/alphacephei/vosk/0.3.38/vosk-0.3.38.jar
unzip -nq vosk-0.3.38.jar
rm -rf META-INF org
rm vosk-0.3.38.jar
cd ../../..
echo 'rootProject.name = "vosk"' > settings.gradle.kts
sed -i '' '10d;21,25d' build.gradle
sed -i '' '80s/^/\/\//' src/main/java/org/vosk/LibVosk.java
sed -i '' '218s/^/\/\//' src/main/java/org/vosk/Recognizer.java
gradle publishToMavenLocal
cd ../..
