package org.openasr.idear.nlp

object Commands {
    val OPEN = "open"
    val SETTINGS = "settings"
    val RECENT = "recent"
    val TERMINAL = "terminal"
    val FOCUS = "focus"
    val EDITOR = "editor"
    val PROJECT = "project"
    val SELECTION = "selection"
    val EXPAND = "grow"
    val SHRINK = "shrink"
    val PRESS = "press"
    val DELETE = "delete"
    val DEBUG = "debug"
    val ENTER = "enter"
    val ESCAPE = "escape"
    val TAB = "tab"
    val UNDO = "undo"
    val NEXT = "next"
    val LINE = "line"
    val PAGE = "page"
    val METHOD = "method"
    val PREVIOUS = "previous"
    val INSPECT_CODE = "inspect code"
    val OKAY_GOOGLE = "okay google"
    val OK_GOOGLE = "ok google"
    val OKAY_IDEA = "okay idea"
    val OK_IDEA = "ok idea"
    val HI_IDEA = "hi idea"
    val WHERE_AM_I = "where am i"
    val NAVIGATE = "navigate"
    val EXECUTE = "execute"
    val GOTO = "goto line"
    val SHOW_USAGES = "show usages"
}