package org.openasr.idear.nlp

object Commands {
    const val OPEN = "open"
    const val SETTINGS = "settings"
    const val RECENT = "recent"
    const val TERMINAL = "terminal"
    const val FOCUS = "focus"
    const val EDITOR = "editor"
    const val PROJECT = "project"
    const val SELECTION = "selection"
    const val GROW = "grow"
    const val SHRINK = "shrink"
    const val PRESS = "press"
    const val DELETE = "delete"
    const val DEBUG = "debug"
    const val ENTER = "enter"
    const val ESCAPE = "escape"
    const val TAB = "tab"
    const val UNDO = "undo"
    const val NEXT = "next"
    const val LINE = "line"
    const val PAGE = "page"
    const val METHOD = "method"
    const val PREVIOUS = "previous"
    const val INSPECT_CODE = "inspect code"
    const val OKAY_IDEA = "okay idea"
    const val OK_IDEA = "ok idea"
    const val HI_IDEA = "hi idea"
    const val WHERE_AM_I = "where am i"
    const val NAVIGATE = "navigate"
    const val EXECUTE = "execute"
    const val GOTO = "goto line"
    const val SHOW_USAGES = "show usages"
}
