{
  parserClass="org.openasr.idear.jsgf.JSpeechParser"
  parserUtilClass="org.openasr.idear.jsgf.JSpeechParserUtil"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="JSpeech"
  psiImplClassSuffix="Impl"
  psiPackage="org.openasr.idear.jsgf.psi"
  psiImplPackage="org.openasr.idear.jsgf.psi.impl"

  elementTypeHolderClass="org.openasr.idear.jsgf.psi.JSpeechTypes"
  elementTypeClass="org.openasr.idear.jsgf.JSpeechElementType"
  tokenTypeClass="org.openasr.idear.jsgf.JSpeechTokenType"

  psiImplUtilClass="org.openasr.idear.jsgf.JSpeechPsiImplUtil"

  tokens = [
      STRING="regexp:[A-Za-z_\-]+\w*"
      NUMBER="regexp:(\+|\-)?\p{Digit}*"
      FLOAT="regexp:(\+|\-)?\p{Digit}*(\.\p{Digit}+)?"

      COMMA=","
      PERIOD="."
      COLON=":"
      SEMICOLON=";"
      EQUALS="="
      BRACE1="{"
      BRACE2="}"
      PAREN1="("
      PAREN2=")"
      BRACKET1="["
      BRACKET2="]"
      BRACKET3="<"
      BRACKET4=">"
      BANG="!"
      OR="|"
      SLASH="/"
      HASH="#"

      PUBLIC="public"
      PRIVATE="private"
      GRAMMAR="grammar"
      VERSION="JSGF V1.0"
    ]
}

grammar ::=
    SelfIdentHeader declaration* ruleDefinition*

ruleDefinition ::=
    scope? rulename '=' ruleExpansion ';'

SelfIdentHeader ::=
    '#JSGF V1.0;'

rulename ::=
    '<' STRING '>' {mixin="org.openasr.idear.jsgf.JSpeechNamedElementImpl"
    implements="org.openasr.idear.jsgf.JSpeechNamedElement"
    methods=[getName setName getRule setRule getNameIdentifier getPresentation]}

literal ::=
    STRING

declaration ::=
    'grammar' STRING ('.' STRING)*';'

scope ::=
    'private' | 'public'

ruleExpansion ::=
    ruleAlternative ( '|' ruleAlternative )*

ruleAlternative ::=
    Weight? sequenceElement+

Weight ::=
    '/' FLOAT '/'

sequenceElement ::=
    subexpansion

subexpansion ::=
    literal
    | rulename
    | '(' ')'
    | '(' ruleExpansion ')'
    | '[' ruleExpansion ']'