{
  parserClass="com.jetbrains.idear.jsgf.JSpeechParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="JSpeech"
  psiImplClassSuffix="Impl"
  psiPackage="com.jetbrains.idear.jsgf.psi"
  psiImplPackage="com.jetbrains.idear.jsgf.psi.impl"

  elementTypeHolderClass="com.jetbrains.idear.jsgf.psi.JSpeechTypes"
  elementTypeClass="com.jetbrains.idear.jsgf.JSpeechElementType"
  tokenTypeClass="com.jetbrains.idear.jsgf.JSpeechTokenType"

  tokens = [
      STRING="regexp:\"[^\"]*\"|'[^']*'"
      NUMBER="regexp:(\+|\-)?\p{Digit}*"
      KEY="regexp:\p{Alpha}\w*"

      COMMA=","
      COLON=":"
      SEMICOLON=";"
      EQUALS="="
      BRACE1="{"
      BRACE2="}"
      PAREN1="("
      PAREN2=")"
      BRACKET1="["
      BRACKET2="]"
      BRACKET3="<"
      BRACKET4=">"
      AT="@"
      DOLLAR="$"
      BANG="!"

      SEPARATOR="="
    ]
}

jsgfile ::= definition*

private definition ::= (rule|COMMENT|CRLF)

rule ::= tag '=' (tag|KEY)+ ';'

tag ::= '<' KEY '>'