/* The following code was generated by JFlex 1.4.3 on 11/13/15 11:59 PM */

package com.jetbrains.idear.jsgf;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static com.jetbrains.idear.jsgf.psi.JSpeechTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/13/15 11:59 PM from the specification file
 * <tt>D:/cygwin/home/breandan/idear/src/com/jetbrains/idear/jsgf/JSpeechLexer.flex</tt>
 */
public class _JSpeechLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\1\1\0\1\1\1\1\22\0\1\51\1\24\1\0"+
    "\1\27\4\0\1\16\1\17\1\0\1\5\1\10\1\2\1\7\1\26"+
    "\1\54\1\53\10\3\1\11\1\12\1\22\1\13\1\23\2\0\5\4"+
    "\1\50\1\47\2\4\1\45\10\4\1\46\2\4\1\52\4\4\1\20"+
    "\1\0\1\21\1\0\1\4\1\0\1\40\1\32\1\35\1\4\1\42"+
    "\1\4\1\43\1\4\1\34\2\4\1\33\1\44\2\4\1\30\1\4"+
    "\1\36\1\4\1\41\1\31\1\37\4\4\1\14\1\25\1\15\u05e2\0"+
    "\12\6\206\0\12\6\306\0\12\6\u019c\0\12\6\166\0\12\6\166\0"+
    "\12\6\166\0\12\6\166\0\12\6\166\0\12\6\166\0\12\6\166\0"+
    "\12\6\166\0\12\6\340\0\12\6\166\0\12\6\106\0\12\6\u0116\0"+
    "\12\6\106\0\12\6\u0746\0\12\6\46\0\12\6\u012c\0\12\6\200\0"+
    "\12\6\246\0\12\6\6\0\12\6\266\0\12\6\126\0\12\6\206\0"+
    "\12\6\6\0\12\6\u89c6\0\12\6\u02a6\0\12\6\46\0\12\6\306\0"+
    "\12\6\166\0\12\6\u0196\0\12\6\u5316\0\12\6\346\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\4\4"+
    "\1\0\1\4\1\26\17\4\1\0\1\27\2\4\1\0"+
    "\1\30\1\31\2\0\1\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[55];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\u010e\0\55"+
    "\0\55\0\55\0\55\0\55\0\55\0\55\0\55\0\55"+
    "\0\55\0\55\0\55\0\55\0\55\0\55\0\55\0\u013b"+
    "\0\u0168\0\u0195\0\u01c2\0\u010e\0\u01ef\0\u010e\0\u021c\0\u0249"+
    "\0\u0276\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\u0357\0\u0384\0\u03b1"+
    "\0\u03de\0\u040b\0\u0438\0\u0465\0\u0492\0\u04bf\0\341\0\u04ec"+
    "\0\u0519\0\u0546\0\341\0\341\0\u0573\0\u05a0\0\55";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[55];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\2\5\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\12\6\1\31\1\6\1\32\3\6\1\3\1\6\2\5"+
    "\56\0\1\3\47\0\1\3\5\0\1\6\1\33\1\6"+
    "\1\0\1\5\1\34\20\0\21\6\1\0\1\6\2\33"+
    "\3\0\1\5\2\0\1\5\1\34\43\0\2\5\2\0"+
    "\1\6\1\35\1\6\23\0\21\6\1\0\1\6\2\35"+
    "\3\0\1\36\2\0\1\36\44\0\2\36\2\0\1\6"+
    "\1\35\1\6\23\0\1\6\1\37\4\6\1\40\12\6"+
    "\1\0\1\6\2\35\2\0\1\6\1\35\1\6\23\0"+
    "\6\6\1\41\12\6\1\0\1\6\2\35\2\0\1\6"+
    "\1\35\1\6\23\0\16\6\1\42\2\6\1\0\1\6"+
    "\2\35\3\0\1\33\1\35\1\0\1\5\1\34\20\0"+
    "\21\35\1\0\1\35\2\33\3\0\2\35\23\0\21\35"+
    "\1\0\3\35\2\0\1\6\1\35\1\6\23\0\2\6"+
    "\1\43\16\6\1\0\1\6\2\35\2\0\1\6\1\35"+
    "\1\6\23\0\4\6\1\44\14\6\1\0\1\6\2\35"+
    "\2\0\1\6\1\35\1\6\23\0\10\6\1\45\10\6"+
    "\1\0\1\6\2\35\2\0\1\6\1\35\1\6\23\0"+
    "\17\6\1\46\1\6\1\0\1\6\2\35\2\0\1\6"+
    "\1\35\1\6\23\0\3\6\1\47\15\6\1\0\1\6"+
    "\2\35\2\0\1\6\1\35\1\6\23\0\7\6\1\50"+
    "\11\6\1\0\1\6\2\35\2\0\1\6\1\35\1\6"+
    "\23\0\14\6\1\51\4\6\1\0\1\6\2\35\2\0"+
    "\1\6\1\35\1\6\23\0\20\6\1\52\1\0\1\6"+
    "\2\35\2\0\1\6\1\35\1\6\23\0\4\6\1\53"+
    "\14\6\1\0\1\6\2\35\2\0\1\6\1\35\1\6"+
    "\23\0\10\6\1\54\10\6\1\0\1\6\2\35\2\0"+
    "\1\6\1\35\1\6\23\0\14\6\1\55\4\6\1\0"+
    "\1\6\2\35\2\0\1\6\1\35\1\6\23\0\21\6"+
    "\1\56\1\6\2\35\2\0\1\6\1\35\1\6\23\0"+
    "\5\6\1\57\13\6\1\0\1\6\2\35\2\0\1\6"+
    "\1\35\1\6\23\0\11\6\1\60\7\6\1\0\1\6"+
    "\2\35\2\0\1\6\1\35\1\6\23\0\10\6\1\61"+
    "\10\6\1\0\1\6\2\35\52\0\1\62\4\0\1\6"+
    "\1\35\1\6\23\0\12\6\1\63\6\6\1\0\1\6"+
    "\2\35\2\0\1\6\1\35\1\6\23\0\6\6\1\64"+
    "\12\6\1\0\1\6\2\35\53\0\1\65\10\0\1\66"+
    "\121\0\1\67";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1485];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\5\1\20\11\4\1\1\0\21\1\1\0"+
    "\3\1\1\0\2\1\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[55];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public _JSpeechLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _JSpeechLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 276) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 23: 
          { return PUBLIC;
          }
        case 27: break;
        case 6: 
          { return COMMA;
          }
        case 28: break;
        case 5: 
          { return PERIOD;
          }
        case 29: break;
        case 24: 
          { return PRIVATE;
          }
        case 30: break;
        case 18: 
          { return BANG;
          }
        case 31: break;
        case 20: 
          { return SLASH;
          }
        case 32: break;
        case 2: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 33: break;
        case 10: 
          { return BRACE1;
          }
        case 34: break;
        case 13: 
          { return PAREN2;
          }
        case 35: break;
        case 15: 
          { return BRACKET2;
          }
        case 36: break;
        case 9: 
          { return EQUALS;
          }
        case 37: break;
        case 7: 
          { return COLON;
          }
        case 38: break;
        case 19: 
          { return OR;
          }
        case 39: break;
        case 11: 
          { return BRACE2;
          }
        case 40: break;
        case 16: 
          { return BRACKET3;
          }
        case 41: break;
        case 8: 
          { return SEMICOLON;
          }
        case 42: break;
        case 26: 
          { return VERSION;
          }
        case 43: break;
        case 22: 
          { return FLOAT;
          }
        case 44: break;
        case 25: 
          { return GRAMMAR;
          }
        case 45: break;
        case 4: 
          { return STRING;
          }
        case 46: break;
        case 1: 
          { return NUMBER;
          }
        case 47: break;
        case 21: 
          { return HASH;
          }
        case 48: break;
        case 3: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 49: break;
        case 14: 
          { return BRACKET1;
          }
        case 50: break;
        case 12: 
          { return PAREN1;
          }
        case 51: break;
        case 17: 
          { return BRACKET4;
          }
        case 52: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
