name: Build & Test

on:
  push:
    branches: [ develop, "release/*" ]
    paths:
      - '**.kt'
      - '**.kts'
      - '**.tidy'
  pull_request:
    branches: [ develop, "release/*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build
      run: ./gradlew test verifyPlugin
