name: Build & Test

on:
  push:
    branches: [ develop ]
    paths:
      - '**.yml'
      - '**.kt'
      - '**.kts'
      - '**.tidy'
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout jAdapterForNativeTTS
      uses: actions/checkout@v3
      with:
        repository: OpenASR/jAdapterForNativeTTS
        ref: fff40ce1a1f1b921272a184acfd0c21350750789
        path: jAdapterForNativeTTS
    - name: Build jAdapterForNativeTTS
      run: cd .jAdapterForNativeTTS && ./gradlew publishToMavenLocal

    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Checkout jAdapterForNativeTTS
      uses: actions/checkout@v3
      with:
        repository: OpenASR/jAdapterForNativeTTS
        path: jAdapterForNativeTTS
    - name: Build jAdapterForNativeTTS
      run: |-
        cd jAdapterForNativeTTS
        mvn install
        ls -al /home/runner/.m2

    - uses: actions/checkout@v3
    - name: Build
      run: ./gradlew test verifyPlugin
