name: Deploy

env:
  ORG_GRADLE_PROJECT_intellijPublishToken: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}

on:
  push:
    branches: [ master ]
#    paths:
#      - '**.kt'
#      - '**.kts'
#      - '**.tidy'
  pull_request:
    branches: [ master ]

jobs:
  Build_and_Publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Needed until Vosk provide a new release to fix Windows issues
      - name: Checkout vosk-api
        uses: actions/checkout@v3
        with:
          repository: alphacep/vosk-api
          ref: fff40ce1a1f1b921272a184acfd0c21350750789
          path: vosk-api
      - name: Download working native libraries
        run: |
          cd vosk-api/java/lib/src/main/resources
          wget -q https://repo1.maven.org/maven2/com/alphacephei/vosk/0.3.38/vosk-0.3.38.jar
          unzip -n vosk-0.3.38.jar
          rm -rf META-INF org
          rm vosk-0.3.38.jar
          cd ../../..
          pwd 
          ls -al
          ./gradlew publishToMavenLocal  

      # Build idear
      - name: Build
        run: |
          ./gradlew test buildPlugin --stacktrace