name: Release to GitHub
# Creates an internal Release in GitHub, but does not publish to IntelliJ Marketplace
# Triggered by creating a "v1.2.3" tag on a release/ or main branch
# Version number is updated as per the tag

on:
  push:
    branches: [ "release/*", main ]
    tags:
      - "v*.*.*"
#  pull_request:
#    branches: [ release/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Update version number
      run: |
        sed -i "s/version = \".*\"/version = \"${GITHUB_REF_NAME:1}\"/" build.gradle.kts

    # Needed until Vosk provide a new release to fix Windows issues
    - name: Checkout vosk-api
      uses: actions/checkout@v3
      with:
        repository: alphacep/vosk-api
        ref: fff40ce1a1f1b921272a184acfd0c21350750789
        path: vosk-api
    - name: Build & install Vosk with working native libraries
      run: |
        cd vosk-api/java/lib/src/main/resources
        wget -q https://repo1.maven.org/maven2/com/alphacephei/vosk/0.3.38/vosk-0.3.38.jar
        unzip -nq vosk-0.3.38.jar
        rm -rf META-INF org
        rm vosk-0.3.38.jar
        cd ../../..
        echo 'rootProject.name = "vosk"' > settings.gradle.kts
        sed -i '10d;21,25d' build.gradle
        gradle publishToMavenLocal

    - name: Build
      run: ./gradlew patchChangelog buildPlugin

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          CHANGELOG.md
          build/libs/*.jar
